apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expressApi
  template:
    metadata:
      labels:
        app: expressApi
    spec:
      containers:
      - name: server
        image: manojlovic1998/fib-server
        ports:
        - containerPort: 5000
