apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib-worker
  template:
    metadata:
      labels:
        app: fib-worker
    spec:
      containers:
      - name: worker
        image: manojlovic1998/fib-worker
